// @flow
'use strict';

import React from 'react';
import Lowlight from 'react-lowlight';
import indexOf from 'lodash.indexof';

//region Imports languages
import oneC from 'highlight.js/lib/languages/1c';
import abnf from 'highlight.js/lib/languages/abnf';
import accesslog from 'highlight.js/lib/languages/accesslog';
import actionscript from 'highlight.js/lib/languages/actionscript';
import ada from 'highlight.js/lib/languages/ada';
import apache from 'highlight.js/lib/languages/apache';
import applescript from 'highlight.js/lib/languages/applescript';
import armasm from 'highlight.js/lib/languages/armasm';
import asciidoc from 'highlight.js/lib/languages/asciidoc';
import aspectj from 'highlight.js/lib/languages/aspectj';
import autohotkey from 'highlight.js/lib/languages/autohotkey';
import autoit from 'highlight.js/lib/languages/autoit';
import avrasm from 'highlight.js/lib/languages/avrasm';
import awk from 'highlight.js/lib/languages/awk';
import axapta from 'highlight.js/lib/languages/axapta';
import bash from 'highlight.js/lib/languages/bash';
import basic from 'highlight.js/lib/languages/basic';
import bnf from 'highlight.js/lib/languages/bnf';
import brainfuck from 'highlight.js/lib/languages/brainfuck';
import cal from 'highlight.js/lib/languages/cal';
import capnproto from 'highlight.js/lib/languages/capnproto';
import ceylon from 'highlight.js/lib/languages/ceylon';
import clean from 'highlight.js/lib/languages/clean';
import clojureRepl from 'highlight.js/lib/languages/clojure-repl';
import clojure from 'highlight.js/lib/languages/clojure';
import cmake from 'highlight.js/lib/languages/cmake';
import coffeescript from 'highlight.js/lib/languages/coffeescript';
import coq from 'highlight.js/lib/languages/coq';
import cos from 'highlight.js/lib/languages/cos';
import cpp from 'highlight.js/lib/languages/cpp';
import crmsh from 'highlight.js/lib/languages/crmsh';
import crystal from 'highlight.js/lib/languages/crystal';
import cs from 'highlight.js/lib/languages/cs';
import csp from 'highlight.js/lib/languages/csp';
import css from 'highlight.js/lib/languages/css';
import d from 'highlight.js/lib/languages/d';
import dart from 'highlight.js/lib/languages/dart';
import delphi from 'highlight.js/lib/languages/delphi';
import diff from 'highlight.js/lib/languages/diff';
import django from 'highlight.js/lib/languages/django';
import dns from 'highlight.js/lib/languages/dns';
import dockerfile from 'highlight.js/lib/languages/dockerfile';
import dos from 'highlight.js/lib/languages/dos';
import dsconfig from 'highlight.js/lib/languages/dsconfig';
import dts from 'highlight.js/lib/languages/dts';
import dust from 'highlight.js/lib/languages/dust';
import ebnf from 'highlight.js/lib/languages/ebnf';
import elixir from 'highlight.js/lib/languages/elixir';
import elm from 'highlight.js/lib/languages/elm';
import erb from 'highlight.js/lib/languages/erb';
import erlangRepl from 'highlight.js/lib/languages/erlang-repl';
import erlang from 'highlight.js/lib/languages/erlang';
import excel from 'highlight.js/lib/languages/excel';
import fix from 'highlight.js/lib/languages/fix';
import flix from 'highlight.js/lib/languages/flix';
import fortran from 'highlight.js/lib/languages/fortran';
import fsharp from 'highlight.js/lib/languages/fsharp';
import gams from 'highlight.js/lib/languages/gams';
import gauss from 'highlight.js/lib/languages/gauss';
import gcode from 'highlight.js/lib/languages/gcode';
import gherkin from 'highlight.js/lib/languages/gherkin';
import glsl from 'highlight.js/lib/languages/glsl';
import go from 'highlight.js/lib/languages/go';
import golo from 'highlight.js/lib/languages/golo';
import gradle from 'highlight.js/lib/languages/gradle';
import groovy from 'highlight.js/lib/languages/groovy';
import haml from 'highlight.js/lib/languages/haml';
import handlebars from 'highlight.js/lib/languages/handlebars';
import haskell from 'highlight.js/lib/languages/haskell';
import haxe from 'highlight.js/lib/languages/haxe';
import hsp from 'highlight.js/lib/languages/hsp';
import htmlbars from 'highlight.js/lib/languages/htmlbars';
import http from 'highlight.js/lib/languages/http';
import hy from 'highlight.js/lib/languages/hy';
import inform7 from 'highlight.js/lib/languages/inform7';
import ini from 'highlight.js/lib/languages/ini';
import irpf90 from 'highlight.js/lib/languages/irpf90';
import java from 'highlight.js/lib/languages/java';
import javascript from 'highlight.js/lib/languages/javascript';
import json from 'highlight.js/lib/languages/json';
import julia from 'highlight.js/lib/languages/julia';
import kotlin from 'highlight.js/lib/languages/kotlin';
import lasso from 'highlight.js/lib/languages/lasso';
import ldif from 'highlight.js/lib/languages/ldif';
import leaf from 'highlight.js/lib/languages/leaf';
import less from 'highlight.js/lib/languages/less';
import lisp from 'highlight.js/lib/languages/lisp';
import livecodeserver from 'highlight.js/lib/languages/livecodeserver';
import livescript from 'highlight.js/lib/languages/livescript';
import llvm from 'highlight.js/lib/languages/llvm';
import lsl from 'highlight.js/lib/languages/lsl';
import lua from 'highlight.js/lib/languages/lua';
import makefile from 'highlight.js/lib/languages/makefile';
import markdown from 'highlight.js/lib/languages/markdown';
import mathematica from 'highlight.js/lib/languages/mathematica';
import matlab from 'highlight.js/lib/languages/matlab';
import maxima from 'highlight.js/lib/languages/maxima';
import mel from 'highlight.js/lib/languages/mel';
import mercury from 'highlight.js/lib/languages/mercury';
import mipsasm from 'highlight.js/lib/languages/mipsasm';
import mizar from 'highlight.js/lib/languages/mizar';
import mojolicious from 'highlight.js/lib/languages/mojolicious';
import monkey from 'highlight.js/lib/languages/monkey';
import moonscript from 'highlight.js/lib/languages/moonscript';
import n1ql from 'highlight.js/lib/languages/n1ql';
import nginx from 'highlight.js/lib/languages/nginx';
import nimrod from 'highlight.js/lib/languages/nimrod';
import nix from 'highlight.js/lib/languages/nix';
import nsis from 'highlight.js/lib/languages/nsis';
import objectivec from 'highlight.js/lib/languages/objectivec';
import ocaml from 'highlight.js/lib/languages/ocaml';
import openscad from 'highlight.js/lib/languages/openscad';
import oxygene from 'highlight.js/lib/languages/oxygene';
import parser3 from 'highlight.js/lib/languages/parser3';
import perl from 'highlight.js/lib/languages/perl';
import pf from 'highlight.js/lib/languages/pf';
import php from 'highlight.js/lib/languages/php';
import pony from 'highlight.js/lib/languages/pony';
import powershell from 'highlight.js/lib/languages/powershell';
import processing from 'highlight.js/lib/languages/processing';
import profile from 'highlight.js/lib/languages/profile';
import prolog from 'highlight.js/lib/languages/prolog';
import protobuf from 'highlight.js/lib/languages/protobuf';
import puppet from 'highlight.js/lib/languages/puppet';
import purebasic from 'highlight.js/lib/languages/purebasic';
import python from 'highlight.js/lib/languages/python';
import q from 'highlight.js/lib/languages/q';
import qml from 'highlight.js/lib/languages/qml';
import r from 'highlight.js/lib/languages/r';
import rib from 'highlight.js/lib/languages/rib';
import roboconf from 'highlight.js/lib/languages/roboconf';
import rsl from 'highlight.js/lib/languages/rsl';
import ruby from 'highlight.js/lib/languages/ruby';
import ruleslanguage from 'highlight.js/lib/languages/ruleslanguage';
import rust from 'highlight.js/lib/languages/rust';
import scala from 'highlight.js/lib/languages/scala';
import scheme from 'highlight.js/lib/languages/scheme';
import scilab from 'highlight.js/lib/languages/scilab';
import scss from 'highlight.js/lib/languages/scss';
import smali from 'highlight.js/lib/languages/smali';
import smalltalk from 'highlight.js/lib/languages/smalltalk';
import sml from 'highlight.js/lib/languages/sml';
import sqf from 'highlight.js/lib/languages/sqf';
import sql from 'highlight.js/lib/languages/sql';
import stan from 'highlight.js/lib/languages/stan';
import stata from 'highlight.js/lib/languages/stata';
import step21 from 'highlight.js/lib/languages/step21';
import stylus from 'highlight.js/lib/languages/stylus';
import subunit from 'highlight.js/lib/languages/subunit';
import swift from 'highlight.js/lib/languages/swift';
import taggerscript from 'highlight.js/lib/languages/taggerscript';
import tap from 'highlight.js/lib/languages/tap';
import tcl from 'highlight.js/lib/languages/tcl';
import tex from 'highlight.js/lib/languages/tex';
import thrift from 'highlight.js/lib/languages/thrift';
import tp from 'highlight.js/lib/languages/tp';
import twig from 'highlight.js/lib/languages/twig';
import typescript from 'highlight.js/lib/languages/typescript';
import vala from 'highlight.js/lib/languages/vala';
import vbnet from 'highlight.js/lib/languages/vbnet';
import vbscriptHtml from 'highlight.js/lib/languages/vbscript-html';
import vbscript from 'highlight.js/lib/languages/vbscript';
import verilog from 'highlight.js/lib/languages/verilog';
import vhdl from 'highlight.js/lib/languages/vhdl';
import vim from 'highlight.js/lib/languages/vim';
import x86asm from 'highlight.js/lib/languages/x86asm';
import xl from 'highlight.js/lib/languages/xl';
import xml from 'highlight.js/lib/languages/xml';
import xquery from 'highlight.js/lib/languages/xquery';
import yaml from 'highlight.js/lib/languages/yaml';
import zephir from 'highlight.js/lib/languages/zephir';
//endregion

//region Registers languages
Lowlight.registerLanguage('1c', oneC);
Lowlight.registerLanguage('abnf', abnf);
Lowlight.registerLanguage('accesslog', accesslog);
Lowlight.registerLanguage('actionscript', actionscript);
Lowlight.registerLanguage('ada', ada);
Lowlight.registerLanguage('apache', apache);
Lowlight.registerLanguage('applescript', applescript);
Lowlight.registerLanguage('armasm', armasm);
Lowlight.registerLanguage('asciidoc', asciidoc);
Lowlight.registerLanguage('aspectj', aspectj);
Lowlight.registerLanguage('autohotkey', autohotkey);
Lowlight.registerLanguage('autoit', autoit);
Lowlight.registerLanguage('avrasm', avrasm);
Lowlight.registerLanguage('awk', awk);
Lowlight.registerLanguage('axapta', axapta);
Lowlight.registerLanguage('bash', bash);
Lowlight.registerLanguage('basic', basic);
Lowlight.registerLanguage('bnf', bnf);
Lowlight.registerLanguage('brainfuck', brainfuck);
Lowlight.registerLanguage('cal', cal);
Lowlight.registerLanguage('capnproto', capnproto);
Lowlight.registerLanguage('ceylon', ceylon);
Lowlight.registerLanguage('clean', clean);
Lowlight.registerLanguage('clojure-repl', clojureRepl);
Lowlight.registerLanguage('clojure', clojure);
Lowlight.registerLanguage('cmake', cmake);
Lowlight.registerLanguage('coffeescript', coffeescript);
Lowlight.registerLanguage('coq', coq);
Lowlight.registerLanguage('cos', cos);
Lowlight.registerLanguage('cpp', cpp);
Lowlight.registerLanguage('crmsh', crmsh);
Lowlight.registerLanguage('crystal', crystal);
Lowlight.registerLanguage('cs', cs);
Lowlight.registerLanguage('csp', csp);
Lowlight.registerLanguage('css', css);
Lowlight.registerLanguage('d', d);
Lowlight.registerLanguage('dart', dart);
Lowlight.registerLanguage('delphi', delphi);
Lowlight.registerLanguage('diff', diff);
Lowlight.registerLanguage('django', django);
Lowlight.registerLanguage('dns', dns);
Lowlight.registerLanguage('dockerfile', dockerfile);
Lowlight.registerLanguage('dos', dos);
Lowlight.registerLanguage('dsconfig', dsconfig);
Lowlight.registerLanguage('dts', dts);
Lowlight.registerLanguage('dust', dust);
Lowlight.registerLanguage('ebnf', ebnf);
Lowlight.registerLanguage('elixir', elixir);
Lowlight.registerLanguage('elm', elm);
Lowlight.registerLanguage('erb', erb);
Lowlight.registerLanguage('erlang-repl', erlangRepl);
Lowlight.registerLanguage('erlang', erlang);
Lowlight.registerLanguage('excel', excel);
Lowlight.registerLanguage('fix', fix);
Lowlight.registerLanguage('flix', flix);
Lowlight.registerLanguage('fortran', fortran);
Lowlight.registerLanguage('fsharp', fsharp);
Lowlight.registerLanguage('gams', gams);
Lowlight.registerLanguage('gauss', gauss);
Lowlight.registerLanguage('gcode', gcode);
Lowlight.registerLanguage('gherkin', gherkin);
Lowlight.registerLanguage('glsl', glsl);
Lowlight.registerLanguage('go', go);
Lowlight.registerLanguage('golo', golo);
Lowlight.registerLanguage('gradle', gradle);
Lowlight.registerLanguage('groovy', groovy);
Lowlight.registerLanguage('haml', haml);
Lowlight.registerLanguage('handlebars', handlebars);
Lowlight.registerLanguage('haskell', haskell);
Lowlight.registerLanguage('haxe', haxe);
Lowlight.registerLanguage('hsp', hsp);
Lowlight.registerLanguage('htmlbars', htmlbars);
Lowlight.registerLanguage('http', http);
Lowlight.registerLanguage('hy', hy);
Lowlight.registerLanguage('inform7', inform7);
Lowlight.registerLanguage('ini', ini);
Lowlight.registerLanguage('irpf90', irpf90);
Lowlight.registerLanguage('java', java);
Lowlight.registerLanguage('javascript', javascript);
Lowlight.registerLanguage('json', json);
Lowlight.registerLanguage('julia', julia);
Lowlight.registerLanguage('kotlin', kotlin);
Lowlight.registerLanguage('lasso', lasso);
Lowlight.registerLanguage('ldif', ldif);
Lowlight.registerLanguage('leaf', leaf);
Lowlight.registerLanguage('less', less);
Lowlight.registerLanguage('lisp', lisp);
Lowlight.registerLanguage('livecodeserver', livecodeserver);
Lowlight.registerLanguage('livescript', livescript);
Lowlight.registerLanguage('llvm', llvm);
Lowlight.registerLanguage('lsl', lsl);
Lowlight.registerLanguage('lua', lua);
Lowlight.registerLanguage('makefile', makefile);
Lowlight.registerLanguage('markdown', markdown);
Lowlight.registerLanguage('mathematica', mathematica);
Lowlight.registerLanguage('matlab', matlab);
Lowlight.registerLanguage('maxima', maxima);
Lowlight.registerLanguage('mel', mel);
Lowlight.registerLanguage('mercury', mercury);
Lowlight.registerLanguage('mipsasm', mipsasm);
Lowlight.registerLanguage('mizar', mizar);
Lowlight.registerLanguage('mojolicious', mojolicious);
Lowlight.registerLanguage('monkey', monkey);
Lowlight.registerLanguage('moonscript', moonscript);
Lowlight.registerLanguage('n1ql', n1ql);
Lowlight.registerLanguage('nginx', nginx);
Lowlight.registerLanguage('nimrod', nimrod);
Lowlight.registerLanguage('nix', nix);
Lowlight.registerLanguage('nsis', nsis);
Lowlight.registerLanguage('objectivec', objectivec);
Lowlight.registerLanguage('ocaml', ocaml);
Lowlight.registerLanguage('openscad', openscad);
Lowlight.registerLanguage('oxygene', oxygene);
Lowlight.registerLanguage('parser3', parser3);
Lowlight.registerLanguage('perl', perl);
Lowlight.registerLanguage('pf', pf);
Lowlight.registerLanguage('php', php);
Lowlight.registerLanguage('pony', pony);
Lowlight.registerLanguage('powershell', powershell);
Lowlight.registerLanguage('processing', processing);
Lowlight.registerLanguage('profile', profile);
Lowlight.registerLanguage('prolog', prolog);
Lowlight.registerLanguage('protobuf', protobuf);
Lowlight.registerLanguage('puppet', puppet);
Lowlight.registerLanguage('purebasic', purebasic);
Lowlight.registerLanguage('python', python);
Lowlight.registerLanguage('q', q);
Lowlight.registerLanguage('qml', qml);
Lowlight.registerLanguage('r', r);
Lowlight.registerLanguage('rib', rib);
Lowlight.registerLanguage('roboconf', roboconf);
Lowlight.registerLanguage('rsl', rsl);
Lowlight.registerLanguage('ruby', ruby);
Lowlight.registerLanguage('ruleslanguage', ruleslanguage);
Lowlight.registerLanguage('rust', rust);
Lowlight.registerLanguage('scala', scala);
Lowlight.registerLanguage('scheme', scheme);
Lowlight.registerLanguage('scilab', scilab);
Lowlight.registerLanguage('scss', scss);
Lowlight.registerLanguage('smali', smali);
Lowlight.registerLanguage('smalltalk', smalltalk);
Lowlight.registerLanguage('sml', sml);
Lowlight.registerLanguage('sqf', sqf);
Lowlight.registerLanguage('sql', sql);
Lowlight.registerLanguage('stan', stan);
Lowlight.registerLanguage('stata', stata);
Lowlight.registerLanguage('step21', step21);
Lowlight.registerLanguage('stylus', stylus);
Lowlight.registerLanguage('subunit', subunit);
Lowlight.registerLanguage('swift', swift);
Lowlight.registerLanguage('taggerscript', taggerscript);
Lowlight.registerLanguage('tap', tap);
Lowlight.registerLanguage('tcl', tcl);
Lowlight.registerLanguage('tex', tex);
Lowlight.registerLanguage('thrift', thrift);
Lowlight.registerLanguage('tp', tp);
Lowlight.registerLanguage('twig', twig);
Lowlight.registerLanguage('typescript', typescript);
Lowlight.registerLanguage('vala', vala);
Lowlight.registerLanguage('vbnet', vbnet);
Lowlight.registerLanguage('vbscript-html', vbscriptHtml);
Lowlight.registerLanguage('vbscript', vbscript);
Lowlight.registerLanguage('verilog', verilog);
Lowlight.registerLanguage('vhdl', vhdl);
Lowlight.registerLanguage('vim', vim);
Lowlight.registerLanguage('x86asm', x86asm);
Lowlight.registerLanguage('xl', xl);
Lowlight.registerLanguage('xml', xml);
Lowlight.registerLanguage('xquery', xquery);
Lowlight.registerLanguage('yaml', yaml);
Lowlight.registerLanguage('zephir', zephir);
//endregion

const LANGUAGES : string[] = [ '1c', 'abnf', 'accesslog', 'actionscript', 'ada', 'apache', 'applescript', 'arduino', 'armasm', 'asciidoc', 'aspectj', 'autohotkey', 'autoit', 'avrasm', 'awk', 'axapta', 'bash', 'basic', 'bnf', 'brainfuck', 'cal', 'capnproto', 'ceylon', 'clean', 'clojure-repl', 'clojure', 'cmake', 'coffeescript', 'coq', 'cos', 'cpp', 'crmsh', 'crystal', 'cs', 'csp', 'css', 'd', 'dart', 'delphi', 'diff', 'django', 'dns', 'dockerfile', 'dos', 'dsconfig', 'dts', 'dust', 'ebnf', 'elixir', 'elm', 'erb', 'erlang-repl', 'erlang', 'excel', 'fix', 'flix', 'fortran', 'fsharp', 'gams', 'gauss', 'gcode', 'gherkin', 'glsl', 'go', 'golo', 'gradle', 'groovy', 'haml', 'handlebars', 'haskell', 'haxe', 'hsp', 'htmlbars', 'http', 'hy', 'inform7', 'ini', 'irpf90', 'java', 'javascript', 'json', 'julia', 'kotlin', 'lasso', 'ldif', 'leaf', 'less', 'lisp', 'livecodeserver', 'livescript', 'llvm', 'lsl', 'lua', 'makefile', 'markdown', 'mathematica', 'matlab', 'maxima', 'mel', 'mercury', 'mipsasm', 'mizar', 'mojolicious', 'monkey', 'moonscript', 'n1ql', 'nginx', 'nimrod', 'nix', 'nsis', 'objectivec', 'ocaml', 'openscad', 'oxygene', 'parser3', 'perl', 'pf', 'php', 'pony', 'powershell', 'processing', 'profile', 'prolog', 'protobuf', 'puppet', 'purebasic', 'python', 'q', 'qml', 'r', 'rib', 'roboconf', 'rsl', 'ruby', 'ruleslanguage', 'rust', 'scala', 'scheme', 'scilab', 'scss', 'smali', 'smalltalk', 'sml', 'sqf', 'sql', 'stan', 'stata', 'step21', 'stylus', 'subunit', 'swift', 'taggerscript', 'tap', 'tcl', 'tex', 'thrift', 'tp', 'twig', 'typescript', 'vala', 'vbnet', 'vbscript-html', 'vbscript', 'verilog', 'vhdl', 'vim', 'x86asm', 'xl', 'xml', 'xquery', 'yaml', 'zephir' ];

export default class CodeRenderer extends React.Component {
    static propTypes : Object;

    shouldComponentUpdate(nextProps : Object) {
        return this.props.inline !== nextProps.inline || this.props.language !== nextProps.language || this.props.literal !== nextProps.literal;
    }

    render() : any {
        return (
            <Lowlight
                inline={this.props.inline}
                language={indexOf(LANGUAGES, this.props.language) >= 0 ? this.props.language : undefined}
                value={this.props.literal} />
        );
    }
}

CodeRenderer.propTypes = {
    inline   : React.PropTypes.bool,
    language : React.PropTypes.string,
    literal  : React.PropTypes.string
};
